### ISSUE TITLE
Injectable Error Logging

### ISSUE THREAD

**Issue by JamiesonRoberts** [estrattonbailey/picoapp#16]
Issue: Because errors are being properly caught, it means that using something like Rollbar or Sentry to capture exceptions for tracking and solving get missed as they aren't actually thrown.

Proposed Idea: The ability to inject a function or some other way to the catch's within pico to then be able to report an outside error logger.

**Comment by estrattonbailey** [comment]
@JamiesonRoberts hey thanks! That's a great idea. Maybe a better solve than what's in there now is to fire off an `error` event instead of logging the exception.

Basically, I think we'd just need to replace [these lines](https://github.com/estrattonbailey/picoapp/blob/master/index.js#L64-L65) with `evx.emit('error')`.

Then you could do `app.on('error', reportToSentry)` or similar.

Would that work for your use case? Would you be interested in having a go at that PR?

**Comment by JamiesonRoberts** [comment]
@estrattonbailey Thats an even better idea for how to handle it. That would definitely work! I'll draft that into a PR shortly!

**Comment by estrattonbailey** [comment]
Added in #17
